In [44]:
#task 1
import numpy as np
array=np.arange(0,9)
print(array)

[0 1 2 3 4 5 6 7 8]


In [53]:
#task 2 
ones=np.ones(9).reshape(3,3)
print(ones)

 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [136]:
#task 3
array=np.arange(1,10)
array[0:11:2]

array([1, 3, 5, 7, 9])

In [127]:
#task 4
array=np.arange(1,10)
array[0:11:2]=-1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1]


In [94]:
#task 5
array=np.arange(1,11).reshape(2,1)
print(array)



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [134]:
#task 6
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
c=np.stack((a,b),axis=-1)
d=np.dot(a,b)
e=np.sum(d,axis=-1)
print(c)
print(d)
print(e)

[[[ 1 10]
  [ 2 11]
  [ 3 12]]

 [[ 4 13]
  [ 5 14]
  [ 6 15]]

 [[ 7 16]
  [ 8 17]
  [ 9 18]]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]
